on:
  push:
    branches:
      - main

name: Build and Deploy to ACI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: "Login to Azure"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and Push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220131:v1
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220131:v1

      - name: "Deploy to ACI"
        uses: "azure/container-instances-deploy@v1"
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: "devops-20220131"
          image: {{ secrets.REGISTRY_LOGIN_SERVER }/20220131:v1
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }
          registry-username: ${{ secrets.REGISTRY_LOGIN_USERNAME }
          registry-password: ${{ secrets.REGISTRY_LOGIN_PASSWORD }
          name: "20220131"
          location: "france south"
